name: Build (amd64 and arm64)

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os-name }} - ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            os-name: Ubuntu 24.04
            arch: amd64
            runner: ubuntu-24.04
          - os: ubuntu-24.04-arm64
            os-name: Ubuntu 24.04 (ARM64)
            arch: arm64
            runner: ubuntu-24.04-arm64
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake build-essential

      - name: Configure (CMake)
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build (CMake)
        run: |
          cmake --build build --config Release -j$(nproc)

      - name: List build outputs
        run: |
          ls -la bin || true
          file bin/* || true

      - name: Prepare per-arch filenames
        run: |
          cp bin/de_ardupilot bin/de_ardupilot-${{ matrix.arch }}

      - name: Upload to GitHub Release (on tags)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            bin/de_ardupilot-${{ matrix.arch }}
            bin/de_mavlink.config.module.json
            bin/template.json
          draft: false
          prerelease: false
